import type { MetadataRoute } from "next";
import { t } from "@/strings";

/**
 * PWA manifest (brief §3 — installed to Android home screen). No offline mode and no
 * service-worker sync queue (brief §2); the SW (src/app/sw.ts) only precaches the shell
 * and serves an offline fallback. Icons are generated by scripts/gen-icons.mjs.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: t.appName,
    short_name: "Home 47",
    description: "Finished-goods stock for Home 47 — record movements, check availability.",
    start_url: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#f5f1eb",
    theme_color: "#1a1a1a",
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
